version: 0.0
os: windows
files:
  - source: .\src\upgrader.exe
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: .\scripts\before-install.bat
      timeout: 900
  AfterInstall:
    - location: .\scripts\run-upgrade.bat
      timeout: 900
